# Site settings
title: Silvan Adrian
email: hallo@silvanadrian.ch
description: > #Web Designer & Entwickler
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://silvanadrian.ch" # the base hostname & protocol for your site

#Author Settings
display_name: Silvan Adrian
gravatar: 60fd5218fff6927c0ed376cce01c5460
twitter: svennebanan_
github: silvanadrian
location: "Zürich, Switzerland"
bio: Informatikstudent und teilzeitarbeitend als Wordpress Entwickler.
# Build settings
markdown: kramdown

excerpt_separator: "<!--more-->"

collections:
  projects:
    output: true
    permalink: /projects/:title.html
    
  images:
    output: true
    permalink: /gallery/:title.html

  experiments:
    output: true
    permalink: /experiment/:title.html  

sass:
    style: :compressed

assets:
    sources:
     - _assets/fonts
     - _assets/javascript
     - _assets/stylesheets
     - _assets/images


   