# Site settings
title: Silvan Adrian
email: hallo@silvanadrian.ch
description: > #Web Designer & Entwickler
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://silvanadrian.ch" # the base hostname & protocol for your site
twitter_username: svennebanan_
github_username:  silvanadrian

# Build settings
markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:title.html
    
  images:
    output: true
    permalink: /gallery/:title.html

  experiments:
    output: true
    permalink: /experiment/:title.html  

sass:
    style: :compressed

assets:
    sources:
     - _assets/fonts
     - _assets/javascript
     - _assets/stylesheets
     - _assets/images
     
defaults:
  -
    scope:
      path: _projects/en
    values:
      layout: default
      lang: en
  -
    scope:
      path: _projects/fr
    values:
      layout: default
      lang: fr
  -
    scope:
      path: _projects/zh
    values:
      layout: default
      lang: zh