# Site settings
title: Silvan Adrian
email: hallo@silvanadrian.ch
description: "Hello and Welcome to the online Home of Switzerland based Frontend Developer Silvan Adrian"
photography: "Travel Photography and my Photographs I took over the years"
projectshead: "My Projects I did over the years"
url: "http://silvanadrian.ch"

#Author Settings
display_name: Silvan Adrian
gravatar: 60fd5218fff6927c0ed376cce01c5460
twitter: svennebanan_
github: silvanadrian
location: "Zürich, Switzerland"
bio: Computer Science Student and part-time Frontend Developer.
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: "<!--more-->"

collections:
  projects:
    output: true
    permalink: /projects/:title.html

  images:
    output: true
    permalink: /gallery/:title.html


sass:
    style: :compressed

assets:
    sources:
     - _assets/fonts
     - _assets/javascript
     - _assets/stylesheets
     - _assets/images

gems:
  - jemoji
  - jekyll-sitemap
